export enum AuthRepositoryEnum {
  AUDIT_REPOSITORY = 'AUDIT_REPOSITORY',
  MENU_REPOSITORY = 'MENU_REPOSITORY',
  PERMISSION_REPOSITORY = 'PERMISSION_REPOSITORY',
  ROLE_REPOSITORY = 'ROLE_REPOSITORY',
  TRANSACTIONAL_CODE_REPOSITORY = 'TRANSACTIONAL_CODE_REPOSITORY',
  USER_REPOSITORY = 'USER_REPOSITORY',
}

export enum CommonRepositoryEnum {
  FILE_REPOSITORY = 'FILE_REPOSITORY',
  CATALOGUE_REPOSITORY = 'CATALOGUE_REPOSITORY',
  DPA_REPOSITORY = 'DPA_REPOSITORY',
  PROVINCE_REPOSITORY = 'PROVINCE_REPOSITORY',
}

export enum CoreRepositoryEnum {
  //entidades estefany
  PLACE_REPOSITORY = 'PLACE_REPOSITORY',
  SHIFT_REPOSITORY = 'SHIFT_REPOSITORY',
  SOCIAL_NETWORK_REPOSITORY = 'SOCIAL_NETWORK_REPOSITORY',
  PLACE_SCHEDULE_REPOSITORY = 'PLACE_SCHEDULES_REPOSITORY',
  /*--------*/
}
